### ISSUE TITLE
Incorrect service identified in stroom/roles/setup/mysql/handlers/main.yml

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom-ansible#10]
Service is identified as `mysql`. It should be `mysqld` as per

```
---
- name: Restart mysql
  service: 
    name: mysqld
    state: restarted
```
