### ISSUE TITLE
Manage RHEL7/RHEL8 software availability deployments

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom-ansible#5]
The common tasks playbook (stroom-ansible-master/stroom/roles/setup/common/tasks/main.yml) should be updated to better support missing software from RHEL8 (which existed in RHEL7). As per
```
# Install common command line tools
- name: YUM install various command line tools
  become: true
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - bash
      - bind-utils # for nslookup
      - coreutils  # realpath is used by some stroom scripts
      - curl
      - git # Needed for migration testing, but useful to have
      - htop # Useful process monitoring
      - iproute  # needed for the ip command used in our scripts
      - jq  # Used by some stroom scripts, handy for REST json munging
      - net-tools
      - python3  # Not sure we need it but just in case
      - unzip
      - vim  # vi is not a mustard cutter

- name: YUM install various command line tools for RHEL7/Centos7 specific deploymen
  become: true
  yum:
    name: "{{ packages_v7 }}"
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_version == '7'
  vars:
    packages_v7:
      - httpie  # Used by some stroom scripts
      - python  # Not sure we need it but just in case
```
